# Generated by Django 4.2.26 on 2025-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('photography', 'Photography'), ('video', 'Video Editing'), ('branding', 'Branding'), ('design', 'Design')], max_length=50, null=True),
        ),
    ]
