# Generated by Django 4.2.26 on 2025-11-22 11:36

from django.db import migrations


def create_initial_superuser(apps, schema_editor):
    """Create initial superuser with portfolio fields"""
    User = apps.get_model('users', 'User')
    
    # Create superuser only if no superuser exists
    if not User.objects.filter(is_superuser=True).exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='@admin123123',
            first_name='محمد',
            last_name='طراد الشمري',
            job_title='Photographer & Designer',
            phone_number='+966570634459',
            location='Riyadh, Saudi Arabia'
        )


def reverse_create_initial_superuser(apps, schema_editor):
    """Delete the initial superuser"""
    User = apps.get_model('users', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_user_model'),
    ]

    operations = [
        migrations.RunPython(create_initial_superuser, reverse_create_initial_superuser),
    ]
