# Generated by Django 4.2.26 on 2025-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_populate_initial_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, help_text='About me section in English', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='about_me_ar',
            field=models.TextField(blank=True, help_text='About me section in Arabic', max_length=2000, null=True),
        ),
    ]
