# Generated by Django 4.2.26 on 2025-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_about_me_user_about_me_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Brief bio in English', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_ar',
            field=models.CharField(blank=True, help_text='Brief bio in Arabic', max_length=250, null=True),
        ),
    ]
