# Generated by Django 4.2.26 on 2025-11-22 11:27

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    """Populate initial data for PortfolioInfo"""
    User = apps.get_model('users', 'User')
    PortfolioInfo = apps.get_model('portfolios', 'PortfolioInfo')
    
    # Get the first superuser
    try:
        user = User.objects.filter(is_superuser=True).first()
        
        if user:
            # Create PortfolioInfo for the superuser
            portfolio_info, created = PortfolioInfo.objects.get_or_create(
                user=user,
                defaults={
                    'portfolio_title': 'We Dream Makers'
                }
            )
    except Exception:
        # If anything fails, skip
        pass


def reverse_populate_initial_data(apps, schema_editor):
    """Reverse the initial data population"""
    PortfolioInfo = apps.get_model('portfolios', 'PortfolioInfo')
    
    # Delete PortfolioInfo for any superuser
    PortfolioInfo.objects.filter(user__is_superuser=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        ('users', '0002_populate_initial_superuser'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_populate_initial_data),
    ]
