# Generated by Django 4.2.26 on 2025-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinfo',
            name='portfolio_title_ar',
            field=models.CharField(default='منصة أعمالي', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='portfolio_title',
            field=models.CharField(default='My Portfolio', max_length=200),
        ),
    ]
