# Generated by Django 4.2.26 on 2025-11-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_category_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category description in English', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Category description in Arabic', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features/services offered'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon name from lucide-react (e.g., 'camera', 'video')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order for frontend'),
        ),
    ]
