# Generated by Django 4.2.26 on 2025-12-03 20:41

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='portfolios/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('gcs_object_name', models.CharField(blank=True, help_text='Full object path/key in GCS for housekeeping', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
