# Generated by Django 4.2.26 on 2025-12-04 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_remove_portfolio_image_portfolio_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='height',
            field=models.IntegerField(blank=True, help_text='Image height in pixels (100-4000)', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(4000)]),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='width',
            field=models.IntegerField(blank=True, help_text='Image width in pixels (100-4000)', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(4000)]),
        ),
    ]
